/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentacion;

import java.awt.Dimension;
import java.awt.Toolkit;

/**
 *
 * @author Danny
 */
public class Inicio extends javax.swing.JFrame {

    /**
     * Creates new form Inicio
     */
    public Inicio() {
        initComponents();
         
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mantDocBtn = new javax.swing.JButton();
        MantExaBtn = new javax.swing.JButton();
        MantHerBtn = new javax.swing.JButton();
        mantPacBtn = new javax.swing.JButton();
        MantSalBtn = new javax.swing.JButton();
        MantUsBtn = new javax.swing.JButton();
        cerrarBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mantDocBtn.setText("Mantenimiento Doctor");
        mantDocBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mantDocBtnActionPerformed(evt);
            }
        });

        MantExaBtn.setText("Mantenimiento Examen Fisico");
        MantExaBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MantExaBtnActionPerformed(evt);
            }
        });

        MantHerBtn.setText("Mantenimiento Herramienta Medica");
        MantHerBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MantHerBtnActionPerformed(evt);
            }
        });

        mantPacBtn.setText("Mantenimiento Paciente");
        mantPacBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mantPacBtnActionPerformed(evt);
            }
        });

        MantSalBtn.setText("Mantenimiento Salon");
        MantSalBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MantSalBtnActionPerformed(evt);
            }
        });

        MantUsBtn.setText("Mantenimiento Usuario");
        MantUsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MantUsBtnActionPerformed(evt);
            }
        });

        cerrarBtn.setText("Cerrar sesion");
        cerrarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cerrarBtnActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setText("SIMAME");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(MantUsBtn)
                            .addComponent(MantSalBtn)
                            .addComponent(mantPacBtn)
                            .addComponent(MantHerBtn)
                            .addComponent(mantDocBtn)
                            .addComponent(MantExaBtn)
                            .addComponent(jLabel1))
                        .addGap(0, 120, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(cerrarBtn)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addGap(29, 29, 29)
                .addComponent(mantDocBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(MantExaBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(MantHerBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mantPacBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(MantSalBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(MantUsBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 114, Short.MAX_VALUE)
                .addComponent(cerrarBtn)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mantDocBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mantDocBtnActionPerformed
        // TODO add your handling code here:
        MantDoctor mDoc = new MantDoctor();
        mDoc.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_mantDocBtnActionPerformed

    private void MantExaBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MantExaBtnActionPerformed
        // TODO add your handling code here:
        MantExamenFisico mExa = new MantExamenFisico();
        mExa.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_MantExaBtnActionPerformed

    private void MantHerBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MantHerBtnActionPerformed
        // TODO add your handling code here:
        MantHerramientaMedica mHer = new MantHerramientaMedica();
        mHer.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_MantHerBtnActionPerformed

    private void mantPacBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mantPacBtnActionPerformed
        // TODO add your handling code here:
        MantPaciente mPac = new MantPaciente();
        mPac.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_mantPacBtnActionPerformed

    private void MantSalBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MantSalBtnActionPerformed
        // TODO add your handling code here:
        MantSalon mSal = new MantSalon();
        mSal.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_MantSalBtnActionPerformed

    private void MantUsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MantUsBtnActionPerformed
        // TODO add your handling code here:
        MantUsuario mUs = new MantUsuario();
        mUs.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_MantUsBtnActionPerformed

    private void cerrarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cerrarBtnActionPerformed
        // TODO add your handling code here:
        VentanaLogin ventana = new VentanaLogin();
        ventana.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_cerrarBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton MantExaBtn;
    private javax.swing.JButton MantHerBtn;
    private javax.swing.JButton MantSalBtn;
    private javax.swing.JButton MantUsBtn;
    private javax.swing.JButton cerrarBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton mantDocBtn;
    private javax.swing.JButton mantPacBtn;
    // End of variables declaration//GEN-END:variables
}
